name: build-validation
on:
  push:
    branches:
      - 'main'
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-macos:
    runs-on: macos-12
    steps:
    - name: Install dependencies
      run: |
        brew install sdl2 libpng glew ninja
    - uses: actions/checkout@v2
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}-ccache
    - name: Build libultraship
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        cmake --no-warn-unused-cli -H. -Bbuild-cmake -GNinja -DCMAKE_BUILD_TYPE:STRING=Release
        cmake --build build-cmake --config Release --parallel 10
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: soh-mac
        path: build-cmake/src/*.a
        if-no-files-found: error
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libpng-dev libglew-dev ninja-build
    - uses: actions/checkout@v2
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}-ccache
    - name: Install latest SDL
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        wget https://www.libsdl.org/release/SDL2-2.24.1.tar.gz
        tar -xzf SDL2-2.24.1.tar.gz
        cd SDL2-2.24.1
        ./configure
        make -j 10
        sudo make install
    - name: Build libultraship
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        cmake --no-warn-unused-cli -H. -Bbuild-cmake -GNinja -DCMAKE_BUILD_TYPE:STRING=Release
        cmake --build build-cmake --config Release --parallel 10
      env:
        CC: gcc-10
        CXX: g++-10
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: soh-linux
        path: build-cmake/src/*.a
        if-no-files-found: error
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Install dependencies
      run: |
        choco install ninja
        Remove-Item -Path "C:\ProgramData\Chocolatey\bin\ccache.exe" -Force
    - uses: actions/checkout@v2
    - name: ccache
      uses: dcvz/ccache-action@27b9f33213c0079872f064f6b6ba0233dfa16ba2
      with:
        key: ${{ runner.os }}-ccache
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Build libultraship
      env:
        VCPKG_ROOT: D:/a/vcpkg
      run: |
        set $env:PATH="$env:USERPROFILE/.cargo/bin;$env:PATH"
        cmake --no-warn-unused-cli -S. -Bbuild-cmake -GNinja -DCMAKE_MAKE_PROGRAM=ninja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DUSE_AUTO_VCPKG=ON -DCMAKE_VS_PLATFORM_NAME=x64
        cmake --build build-cmake --config Release --parallel 10
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: soh-windows
        path: build-cmake/src/**/*.lib
        if-no-files-found: error
